name: dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      environment:
        description: 'Enviroment'
        required: true
        type: environment
      matrix:
        description: 'Strategy matrix'
        required: true
        type: string


jobs:
  log-the-inputs:
    strategy:
      matrix: ${{ fromJSON(inputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'name'
        run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          ENVIRONMENT: ${{ inputs.environment }}
